# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-08-21 11:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommnetManage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('content', models.TextField(blank=True, null=True, verbose_name='评论内容')),
                ('service', models.IntegerField(choices=[(1, '1星'), (2, '2星'), (3, '3星'), (4, '4星'), (5, '5星')], verbose_name='服务星级评分')),
                ('environment', models.IntegerField(choices=[(1, '1星'), (2, '2星'), (3, '3星'), (4, '4星'), (5, '5星')], verbose_name='环境星级评分')),
                ('comment_img', models.ImageField(blank=True, null=True, upload_to='comment', verbose_name='评论图片')),
            ],
            options={
                'verbose_name': '评论列表',
                'verbose_name_plural': '评论列表',
                'db_table': 'CommnetManage',
            },
        ),
    ]
