# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-08-21 11:23
from __future__ import unicode_literals

import DjangoUeditor.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store2User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('store_water_num', models.IntegerField(blank=True, null=True, verbose_name='流水编号')),
                ('store_source', models.IntegerField(blank=True, choices=[(0, '洗车'), (1, '活动'), (2, '提现'), (3, '核销')], null=True, verbose_name='来源')),
                ('store_money', models.PositiveIntegerField(blank=True, null=True, verbose_name='交易金额(单位分)')),
                ('user_water_num', models.IntegerField(blank=True, null=True, verbose_name='流水编号')),
                ('user_source', models.IntegerField(blank=True, choices=[(0, '洗车'), (1, '活动'), (2, '充值')], null=True, verbose_name='来源')),
                ('user_money', models.PositiveIntegerField(blank=True, null=True, verbose_name='交易金额(单位分)')),
            ],
            options={
                'verbose_name': '商家/用户钱包流水',
                'verbose_name_plural': '商家/用户钱包流水',
                'db_table': 'StoreWallet',
            },
        ),
        migrations.CreateModel(
            name='StoreManage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('linkman', models.CharField(blank=True, max_length=20, null=True, verbose_name='联系人姓名')),
                ('store_name', models.CharField(blank=True, max_length=20, null=True, verbose_name='店名')),
                ('store_add', models.CharField(max_length=100, verbose_name='店铺地址')),
                ('up_five_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='5座以上价格')),
                ('low_five_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='5座以下价格')),
                ('service', models.CharField(choices=[('标准洗车', 0), ('精致洗车', 1)], max_length=4, verbose_name='服务内容选择')),
                ('graded', models.CharField(blank=True, max_length=5, null=True, verbose_name='评分')),
                ('area', models.CharField(blank=True, max_length=20, null=True, verbose_name='区域')),
                ('location', models.CharField(blank=True, max_length=100, null=True, verbose_name='定位')),
                ('office_hours', models.TimeField(blank=True, null=True, verbose_name='上班时间')),
                ('closing_time', models.TimeField(blank=True, null=True, verbose_name='下班时间')),
                ('commission_rate', models.DecimalField(decimal_places=4, max_digits=5, verbose_name='佣金比例')),
                ('account', models.CharField(max_length=50, verbose_name='账号')),
                ('password', models.CharField(blank=True, max_length=20, null=True, verbose_name='密码')),
                ('bank_num', models.IntegerField(blank=True, null=True, verbose_name='银行卡号')),
                ('cardholder', models.CharField(blank=True, max_length=20, null=True, verbose_name='持卡人')),
                ('belong_bank', models.CharField(blank=True, max_length=100, null=True, verbose_name='所属银行')),
                ('service_content', models.TextField(blank=True, null=True, verbose_name='服务内容')),
                ('phone', models.CharField(blank=True, max_length=11, null=True, verbose_name='联系电话')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='media/store/logo', verbose_name='店铺的logo')),
                ('store_img', models.ImageField(blank=True, null=True, upload_to='media/store', verbose_name='店铺图片')),
                ('detail', DjangoUeditor.models.UEditorField(default='', verbose_name='门店详情')),
                ('audit_status', models.IntegerField(choices=[(0, '通过审核'), (1, '未通过审核')], default='未通过审核', verbose_name='审核状态')),
                ('status', models.SmallIntegerField(choices=[(1, '空闲'), (2, '忙碌'), (3, '休息')], default=1, verbose_name='商家状态')),
                ('shop_lon', models.FloatField(blank=True, null=True, verbose_name='店铺经度')),
                ('shop_lat', models.FloatField(blank=True, null=True, verbose_name='店铺维度')),
                ('all_service_charge', models.PositiveIntegerField(blank=True, null=True, verbose_name='总手续费(单位分)')),
                ('balance', models.PositiveIntegerField(blank=True, null=True, verbose_name='余额(单位分)')),
                ('sub_store_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.StoreManage', verbose_name='子账户')),
            ],
            options={
                'verbose_name': '门店',
                'verbose_name_plural': '门店',
                'db_table': 'store',
            },
        ),
    ]
