# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-08-21 11:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='storemanage',
            name='user',
            field=models.ManyToManyField(through='store.Store2User', to='users.User', verbose_name='微信用户'),
        ),
        migrations.AddField(
            model_name='store2user',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.StoreManage'),
        ),
        migrations.AddField(
            model_name='store2user',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.User'),
        ),
        migrations.CreateModel(
            name='UserWater',
            fields=[
            ],
            options={
                'verbose_name': '用户钱包流水',
                'verbose_name_plural': '用户钱包流水',
                'db_table': 'shopuser',
                'proxy': True,
                'indexes': [],
            },
            bases=('store.store2user',),
        ),
    ]
