# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-08-21 11:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('headline', models.CharField(blank=True, max_length=50, null=True, verbose_name='标题')),
                ('content', models.TextField(blank=True, max_length=500, null=True, verbose_name='内容')),
                ('check_status', models.IntegerField(choices=[(0, '已阅'), (1, '未阅')], verbose_name='审核状态')),
            ],
            options={
                'verbose_name': '反馈建议列表',
                'verbose_name_plural': '反馈建议列表',
                'db_table': 'Feedback',
            },
        ),
        migrations.CreateModel(
            name='Textmng',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user_agreement', models.TextField(blank=True, null=True, verbose_name='用户协议')),
                ('point_rule', models.TextField(blank=True, null=True, verbose_name='积分规则说明')),
                ('about_us', models.TextField(blank=True, null=True, verbose_name='关于我们')),
            ],
            options={
                'verbose_name': '文本列表',
                'verbose_name_plural': '文本列表',
                'db_table': 'Textmng',
            },
        ),
        migrations.CreateModel(
            name='StoreApplay',
            fields=[
            ],
            options={
                'verbose_name': '商家申请列表',
                'verbose_name_plural': '商家申请列表',
                'db_table': 'StoreApplay',
                'proxy': True,
                'indexes': [],
            },
            bases=('store.storemanage',),
        ),
    ]
