# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-08-21 11:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('discount_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='优惠券名称')),
                ('discount_num', models.IntegerField(verbose_name='优惠券编号')),
                ('discount_money', models.IntegerField(verbose_name='优惠券金额')),
                ('validity_time', models.IntegerField(verbose_name='优惠券有效期')),
                ('discount_status', models.BooleanField(default=False, verbose_name='优惠券状态,默认为失效')),
            ],
            options={
                'verbose_name': '优惠券',
                'verbose_name_plural': '优惠券',
            },
        ),
    ]
