# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-08-21 11:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OverApply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('check_status', models.IntegerField(choices=[(0, '通过'), (1, '不通过')], verbose_name='审核状态')),
                ('withdraw_money', models.PositiveIntegerField(blank=True, null=True, verbose_name='提现金额(单位分)')),
                ('num', models.IntegerField(default=0, verbose_name='提现次数')),
                ('service_money', models.PositiveIntegerField(blank=True, null=True, verbose_name='单次提现手续费(单位分)')),
            ],
            options={
                'verbose_name': '申请提现列表',
                'verbose_name_plural': '申请提现列表',
                'db_table': 'OverApply',
            },
        ),
    ]
