# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-08-21 11:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0001_initial'),
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreWallet',
            fields=[
            ],
            options={
                'verbose_name': '商家钱包',
                'verbose_name_plural': '商家钱包',
                'db_table': 'StoreWallet',
                'proxy': True,
                'indexes': [],
            },
            bases=('store.storemanage',),
        ),
    ]
