# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-08-21 11:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0001_initial'),
        ('finance', '0002_storewallet'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserWallet',
            fields=[
            ],
            options={
                'verbose_name': '用户钱包',
                'verbose_name_plural': '用户钱包',
                'db_table': 'UserWallet',
                'proxy': True,
                'indexes': [],
            },
            bases=('users.user',),
        ),
        migrations.AddField(
            model_name='overapply',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.StoreManage', verbose_name='商店'),
        ),
        migrations.CreateModel(
            name='IsOverApply',
            fields=[
            ],
            options={
                'verbose_name': '已提现',
                'verbose_name_plural': '已提现',
                'db_table': 'IsOverApply',
                'proxy': True,
                'indexes': [],
            },
            bases=('finance.overapply',),
        ),
    ]
