# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2019-08-21 11:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('adver_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='广告名称')),
                ('adver_img', models.ImageField(blank=True, null=True, upload_to='adver', verbose_name='广告图片')),
                ('adver_img_url', models.CharField(blank=True, max_length=200, null=True, verbose_name='广告图片超链接')),
            ],
            options={
                'verbose_name': '广告列表',
                'verbose_name_plural': '广告列表',
                'db_table': 'Adver',
            },
        ),
    ]
